"""Signal domain models for Turtle Trading system."""

from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, Field

from src.domain.models.enums import Direction, System


class Signal(BaseModel):
    """A trading signal generated by breakout detection.

    Immutable value object representing a potential entry opportunity.
    """

    model_config = {"frozen": True}

    symbol: str
    direction: Direction
    system: System
    breakout_price: Decimal = Field(..., description="Price that triggered the breakout")
    channel_value: Decimal = Field(..., description="Donchian channel value breached")
    detected_at: datetime = Field(default_factory=datetime.now)

    @property
    def is_long(self) -> bool:
        """Check if this is a long signal."""
        return self.direction == Direction.LONG

    @property
    def is_s1(self) -> bool:
        """Check if this is a System 1 signal."""
        return self.system == System.S1


class FilterResult(BaseModel):
    """Result of S1 filter evaluation.

    The S1 filter skips signals if the previous S1 trade was a winner.
    S2 signals are never filtered (failsafe rule).
    """

    model_config = {"frozen": True}

    take_signal: bool = Field(..., description="Whether to take this signal")
    reason: str = Field(..., description="Explanation for the decision")
    last_s1_was_winner: bool | None = Field(
        default=None,
        description="Whether the last S1 trade was a winner (None if no history)",
    )
    signal: Signal | None = Field(default=None, description="The evaluated signal")

    @classmethod
    def accept(cls, signal: Signal, reason: str = "Signal accepted") -> "FilterResult":
        """Create an accepting filter result."""
        return cls(take_signal=True, reason=reason, signal=signal)

    @classmethod
    def reject(
        cls, signal: Signal, reason: str, last_s1_was_winner: bool | None = None
    ) -> "FilterResult":
        """Create a rejecting filter result."""
        return cls(
            take_signal=False,
            reason=reason,
            last_s1_was_winner=last_s1_was_winner,
            signal=signal,
        )
